//! Obsidian vault integration: directory layout, analysis notes, the
//! exchange JSON archive and the auto-generated historical dashboard.

use anyhow::{Context, Result};
use std::path::{Path, PathBuf};

use crate::charts::snapshot_charts;
use crate::config::VaultConfig;
use crate::history::HistoryFile;

pub struct Vault<'a> {
    cfg: &'a VaultConfig,
}

impl<'a> Vault<'a> {
    pub fn new(cfg: &'a VaultConfig) -> Self {
        Self { cfg }
    }

    pub fn root(&self) -> &Path {
        &self.cfg.path
    }

    pub fn analyses_dir(&self) -> PathBuf {
        self.cfg.path.join(&self.cfg.analyses_dir)
    }

    pub fn dashboard_file(&self) -> PathBuf {
        self.cfg
            .path
            .join(&self.cfg.dashboard_dir)
            .join("Dashboard.md")
    }

    pub fn exchange_dir(&self) -> PathBuf {
        self.cfg.path.join(&self.cfg.assets_dir).join("exchange")
    }

    /// Create the vault directory structure (idempotent) and seed the
    /// analysis template on first run.
    pub fn ensure_layout(&self) -> Result<()> {
        for dir in [
            self.cfg.path.clone(),
            self.analyses_dir(),
            self.cfg.path.join(&self.cfg.dashboard_dir),
            self.cfg.path.join(&self.cfg.templates_dir),
            self.cfg.path.join(&self.cfg.assets_dir),
            self.exchange_dir(),
        ] {
            std::fs::create_dir_all(&dir)
                .with_context(|| format!("cannot create vault directory {}", dir.display()))?;
        }
        let template = self
            .cfg
            .path
            .join(&self.cfg.templates_dir)
            .join("Analysis Template.md");
        if !template.exists() {
            std::fs::write(
                &template,
                "# Trading Analysis\n\nGenerated by trade-analyzer. Run `trade-analyzer analyze <csv>` to create analyses.\n",
            )?;
        }
        Ok(())
    }

    /// Write an analysis note. `stamp` must be `YYYY-MM-DD_HH-mm`.
    pub fn write_analysis(&self, stamp: &str, markdown: &str) -> Result<PathBuf> {
        let path = self.analyses_dir().join(format!("{stamp}.md"));
        std::fs::write(&path, markdown)
            .with_context(|| format!("cannot write analysis {}", path.display()))?;
        Ok(path)
    }

    /// Archive the exchange JSON for the AI layer and future comparisons.
    pub fn write_exchange_json(&self, stamp: &str, json: &str) -> Result<PathBuf> {
        let path = self.exchange_dir().join(format!("{stamp}.json"));
        std::fs::write(&path, json)
            .with_context(|| format!("cannot write exchange JSON {}", path.display()))?;
        Ok(path)
    }

    /// Regenerate `Dashboard.md`: the historical analytics dashboard with
    /// development charts over every stored analysis, plus links to every
    /// analysis note (newest first).
    pub fn update_dashboard(&self, history: &HistoryFile) -> Result<PathBuf> {
        let mut stems: Vec<String> = Vec::new();
        if self.analyses_dir().exists() {
            for entry in std::fs::read_dir(self.analyses_dir())? {
                let entry = entry?;
                let path = entry.path();
                if path.extension().and_then(|e| e.to_str()) == Some("md") {
                    if let Some(stem) = path.file_stem().and_then(|s| s.to_str()) {
                        stems.push(stem.to_string());
                    }
                }
            }
        }
        // Filename stamps sort chronologically; newest first.
        stems.sort();
        stems.reverse();

        let mut content = String::from("# Trading Dashboard\n\n");
        content.push_str(&format!(
            "{} analyses on record.\n\n",
            history.snapshots.len()
        ));

        // Historical development charts (from the second analysis onward).
        let charts = snapshot_charts(&history.snapshots);
        let sections: [(&str, &Option<crate::charts::ChartSpec>); 8] = [
            ("Total PnL per Analysis", &charts.total_pnl),
            ("Win Rate", &charts.win_rate),
            ("Profit Factor", &charts.profit_factor),
            ("Average RR", &charts.average_rr),
            ("Average Weekly PnL", &charts.weekly_pnl),
            ("Average Monthly PnL", &charts.monthly_pnl),
            ("Max Daily Drawdown", &charts.max_drawdown),
            ("Score Development", &charts.scores),
        ];
        let mut any_chart = false;
        for (title, spec) in sections {
            if let Some(spec) = spec {
                content.push_str(&format!("## {title}\n\n"));
                content.push_str(&spec.render());
                content.push('\n');
                any_chart = true;
            }
        }
        if !any_chart && !history.snapshots.is_empty() {
            content.push_str("_Development charts appear from the second analysis onward._\n\n");
        }

        content.push_str("## Analyses\n\n");
        if stems.is_empty() {
            content.push_str("_No analyses yet. Run `trade-analyzer analyze <csv>`._\n");
        } else {
            for stem in &stems {
                content.push_str(&format!("[[{stem}]]\n\n"));
            }
        }

        let path = self.dashboard_file();
        std::fs::write(&path, content)
            .with_context(|| format!("cannot write dashboard {}", path.display()))?;
        Ok(path)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn temp_vault_cfg(name: &str) -> VaultConfig {
        let path = std::env::temp_dir()
            .join("trade-analyst-vault-tests")
            .join(name);
        let _ = std::fs::remove_dir_all(&path);
        VaultConfig {
            path,
            ..VaultConfig::default()
        }
    }

    fn snapshot(at: &str, win_rate: f64) -> crate::history::Snapshot {
        crate::history::Snapshot {
            generated_at: at.to_string(),
            source_file: "t.csv".into(),
            report_file: None,
            total_trades: 10,
            total_pnl: 100.0,
            win_rate,
            profit_factor: Some(2.0),
            average_rr: Some(1.5),
            average_trade: 10.0,
            average_weekly_pnl: 50.0,
            average_monthly_pnl: 100.0,
            max_daily_drawdown: 30.0,
            discipline_score: 70.0,
            consistency_score: 60.0,
            emotional_control_score: 80.0,
            best_pair: None,
            best_pair_pnl: None,
        }
    }

    fn empty_history() -> HistoryFile {
        HistoryFile {
            schema_version: "1.1.0".into(),
            snapshots: vec![],
        }
    }

    #[test]
    fn layout_and_dashboard() {
        let cfg = temp_vault_cfg("layout");
        let vault = Vault::new(&cfg);
        vault.ensure_layout().unwrap();
        assert!(vault.analyses_dir().exists());
        assert!(vault.exchange_dir().exists());

        vault
            .write_analysis("2026-01-05_10-00", "# Trading Dashboard\n")
            .unwrap();
        vault
            .write_analysis("2026-02-10_15-30", "# Trading Dashboard\n")
            .unwrap();
        let dashboard = vault.update_dashboard(&empty_history()).unwrap();
        let content = std::fs::read_to_string(dashboard).unwrap();
        let first = content.find("[[2026-02-10_15-30]]").unwrap();
        let second = content.find("[[2026-01-05_10-00]]").unwrap();
        assert!(first < second, "dashboard must list newest first");
    }

    #[test]
    fn dashboard_renders_history_charts_from_two_snapshots() {
        let cfg = temp_vault_cfg("history-charts");
        let vault = Vault::new(&cfg);
        vault.ensure_layout().unwrap();

        let one = HistoryFile {
            schema_version: "1.1.0".into(),
            snapshots: vec![snapshot("2026-01-01T10:00:00", 50.0)],
        };
        let content = std::fs::read_to_string(vault.update_dashboard(&one).unwrap()).unwrap();
        assert!(!content.contains("```chart"));
        assert!(content.contains("_Development charts appear from the second analysis onward._"));

        let two = HistoryFile {
            schema_version: "1.1.0".into(),
            snapshots: vec![
                snapshot("2026-01-01T10:00:00", 50.0),
                snapshot("2026-02-01T10:00:00", 60.0),
            ],
        };
        let content = std::fs::read_to_string(vault.update_dashboard(&two).unwrap()).unwrap();
        assert!(content.contains("## Win Rate"));
        assert!(content.contains("## Score Development"));
        assert!(content.matches("```chart").count() >= 6);
    }

    #[test]
    fn ensure_layout_is_idempotent() {
        let cfg = temp_vault_cfg("idempotent");
        let vault = Vault::new(&cfg);
        vault.ensure_layout().unwrap();
        vault.ensure_layout().unwrap();
        let _ = vault.update_dashboard(&empty_history()).unwrap();
    }
}
